### PR TITLE
Hello there!

### PR DESCRIPTION
**Pull request by Schweinepriester**

### CODE REVIEW

**Comment by Schweinepriester** [comment]
nice that you can update PR titles after the fact 🙃

**Comment by supermavster** [comment]
Hi @Schweinepriester I have a question

With your own repository and your own merge, you can get the achievement?

I trie differents ways but not working :c

**Comment by supermavster** [comment]
haha works, when i write and update the readme and merge :v haha thanks

**Comment by Schweinepriester** [comment]
Curious that it worked for you without having a reviewer assigned!

https://github.com/supermavster/achievement-testarea/pull/1

**Comment by nishat-nasir** [comment]
cool

**Comment by JhonnyLusonode** [comment]
hm lets test it out

**Comment by GuilhermeCruzPT** [comment]
how can i get the YOLO achievement i try but not working :c

**Comment by porosh2002** [comment]
123

**Comment by Svendolin** [comment]
cute-dog

Hello there, big flouff!

**Comment by ilham89** [comment]
test

**Comment by praveenscience** [comment]
Hey @Schweinepriester, how long did it take for you to get the yolo badge for this one? Does it take some time to show it up in your profile? Plus is it possible to get this now, like today? Thanks... 😊

**Comment by Schweinepriester** [comment]
Hey @praveenscience - it was instant for me.

But we have indication that they are still tinkering with the achievements, e.g. https://github.com/Schweinepriester/github-profile-achievements/discussions/91, so things might have changed…

**Comment by praveenscience** [comment]
> Hey @praveenscience - it was instant for me.
> 
> But we have indication that they are still tinkering with the achievements, e.g. [Schweinepriester/github-profile-achievements#91](https://github.com/Schweinepriester/github-profile-achievements/discussions/91), so things might have changed…

Ah, okay sure @Schweinepriester! Let's wait and see...

**Comment by Jirina2181** [comment]
Thanks

**Comment by dookki** [comment]
At this time, can YOLO badges still be obtained?

**Comment by Schweinepriester** [comment]
Future explorers: For further questions, please open a discussion in the main repo at https://github.com/Schweinepriester/github-profile-achievements/discussions :)

**Pull request merged**
