### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Schweinepriester**

### CODE REVIEW

**Comment by Jirina2181** [comment]
Thanks

**Comment by chippeddog** [comment]
Thank you!

**Comment by Baihaki123** [comment]
thanks you

**Comment by d4tdev** [comment]
Thanks you!

**Comment by FrontEndProfile** [comment]
thanks

**Comment by Pathum-lakshan** [comment]
tt

**Comment by Jirina2181** [comment]
Diky

**Comment by murilofray** [comment]
Thanks

**Comment by aragonxpd154** [comment]
thanks

**Comment by joaoguilherme000** [comment]
thank you 🤓

**Comment by AbrarShakilAhmed** [comment]
thanks

**Pull request closed without merging**
